name: CI/CD Pipeline - Deploy to AWS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Copy files via SSH/SCP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "app,frontend,Dockerfile,requirements.txt"
        target: "/home/ec2-user/REAL-TIME-VOICE-PIPELINE"

    - name: Run Deploy Script on EC2
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        command_timeout: 10m
        script: |
          cd /home/ec2-user/REAL-TIME-VOICE-PIPELINE
          touch .env
          (docker build -t voice-pipeline-app . || sudo -n docker build -t voice-pipeline-app .)
          (docker stop voice-pipeline || sudo -n docker stop voice-pipeline || true)
          (docker rm voice-pipeline || sudo -n docker rm voice-pipeline || true)
          (docker run -d --name voice-pipeline --restart always -p 8000:8000 --env-file .env voice-pipeline-app || sudo -n docker run -d --name voice-pipeline --restart always -p 8000:8000 --env-file .env voice-pipeline-app)
